const ADDITIONAL_CSV = process.env.ADDITIONAL_EXTERNAL_EVENT_TYPES_CSV ?? '';

export const EXTERNAL_EVENT_TYPES: string[] = [
  'PEER_JWS_CONFIGURED',
  'DFSP_JWS_PROPAGATED',
  'DFSP_CA_PROPAGATED',
  'DFSP_SERVER_CERT_CONFIGURED',
  'DFSP_CLIENT_CERT_CONFIGURED',
  'HUB_CLIENT_CERT_SIGNED',
  'ENDPOINT_CONFIG_PROPAGATED',
  'UPLOADING_DFSP_CSR',
  ...(ADDITIONAL_CSV).split(',').filter(Boolean)
] as const;
